// musicData.js
const songs = [
  {
    id: 1,
    title: "Diary Despresiku",
    displayTitle: "Diary Despresiku", // Judul yang ditampilkan di card
    artist: "Last Child",
    audioSrc: "audio/diarydespresiku.mp3", // Path ke audio MP3
    imageSrc: "images/diarydespresiku.jpg", // Path ke gambar thumbnail
    lyricsPath: "lyrics/diarydespresiku.json", // Path ke lirik
  },
  {
    id: 2,
    title: "tarot",
    displayTitle: "tarot",
    artist: "FEAST",
    audioSrc: "audio/tarot.mp3",
    imageSrc: "images/tarot.jpg",
    lyricsPath: "lyrics/tarot.json",
  },
  {
    id: 3,
    title: "Nina",
    displayTitle: "Nina",
    artist: "FEAST",
    audioSrc: "audio/nina.mp3",
    imageSrc: "images/nina.jpg",
    lyricsPath: "lyrics/nina.json",
  },
    {
    id: 4,
    title: "Apa Mungkin Pop Punk",
    displayTitle: "Apa Mungkin Pop Punk",
    artist: "Bernadya",
    audioSrc: "audio/bernadya.mp3",
    imageSrc: "images/bernadya.jpg",
    lyricsPath: "lyrics/Bernadya.json",
    lyricsPath: "lyrics/bernadya.json",
  },
  {
    id: 5,
    title: "hujan Pop Punk",
    displayTitle: "hujan Pop Punk",
    artist: "",
    audioSrc: "audio/hujan.mp3",
    imageSrc: "images/hujan.jpg",
    lyricsPath: "lyrics/Bernadya.json",
  },
    {
    id: 6,
    title: "bunga maaf Pop Punk",
    displayTitle: "bunga maaf Pop Punk",
    artist: "",
    audioSrc: "audio/bunga maaf.mp3",
    imageSrc: "images/bungamaaf.jpg",
    lyricsPath: "lyrics/bungamaaf.json",
  },
      {
    id: 7,
    title: "untungnnya Pop Punk",
    displayTitle: "untungnya Pop Punk",
    artist: "",
    audioSrc: "audio/untungnnya.mp3",
    imageSrc: "images/untungnnya.jpg",
    lyricsPath: "lyrics/.json",
  },
        {
    id: 8,
    title: "KekasihBayangan Pop Punk",
    displayTitle: "KekasihBayangan Pop Punk",
    artist: "",
    audioSrc: "audio/kekasih bayangan.mp3",
    imageSrc: "images/kekasih bayangan.jpg",
    lyricsPath: "lyrics/.json",
  },
          {
    id: 9,
    title: "kekasih tolol Pop Punk",
    displayTitle: "kekasih tolol Pop Punk",
    artist: "",
    audioSrc: "audio/kekasih tolol.mp3",
    imageSrc: "images/kekasih tolol.jpg",
    lyricsPath: "lyrics/.json",
  },
            {
    id: 10,
    title: "tetaplah bersamaku",
    displayTitle: "tetaplah bersamaku",
    artist: "",
    audioSrc: "audio/tetaplah bersamaku.mp3",
    imageSrc: "images/tetaplah bersamaku.jpg",
    lyricsPath: "lyrics/.json",
  },
              {
    id: 11,
    title: "sunset tanah anarki",
    displayTitle: "sunset tanah anarki",
    artist: "",
    audioSrc: "audio/sunset tanah anarki.mp3",
    imageSrc: "images/sunset tanah anarki.jpg",
    lyricsPath: "lyrics/.json",
  },
              {
    id: 12,
    title: "aku kamu dan samudra",
    displayTitle: "aku kamu dan samudra",
    artist: "",
    audioSrc: "audio/aku kamu dan samudra.mp3",
    imageSrc: "images/aku kamu dan samudra.jpg",
    lyricsPath: "lyrics/.json",
  },
                {
    id: 13,
    title: "ada aku di sini",
    displayTitle: "ada aku di sini",
    artist: "",
    audioSrc: "audio/ada aku di sini.mp3",
    imageSrc: "images/ada aku di sini.jpg",
    lyricsPath: "lyrics/.json",
  },
  {
      id: 14,
    title: "wanita masih banyak",
    displayTitle: "wanita masih banyak",
    artist: "",
    audioSrc: "audio/wanita masih banyak.mp3",
    imageSrc: "images/wanita masih banyak.jpg",
    lyricsPath: "lyrics/.json",
  },
    {
      id: 15,
    title: "bondan rip",
    displayTitle: "bondan rip",
    artist: "",
    audioSrc: "audio/bondan rip.mp3",
    imageSrc: "images/bondan rip.jpg",
    lyricsPath: "lyrics/.json",
  },
      {
      id: 16,
    title: "mawar hitam",
    displayTitle: "mawar hitam",
    artist: "",
    audioSrc: "audio/mawar hitam.mp3",
    imageSrc: "images/mawar hitam.jpg",
    lyricsPath: "lyrics/.json",
  },
  {
        id: 17,
    title: "gembira adalah obat",
    displayTitle: "gembira adalah obat",
    artist: "",
    audioSrc: "audio/gembira adalah obat.mp3",
    imageSrc: "images/gembira adalah obat.jpg",
    lyricsPath: "lyrics/.json",
  },
  // Tambahkan lagu lainnya di sini
];
